on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Linux
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller -F -n=VoltageLabLinux --clean --additional-hooks-dir=. voltage_lab.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VoltageLabLinux
        path: dist

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build MacOS
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller -F -n=VoltageLabMacOS --clean --additional-hooks-dir=. voltage_lab.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VoltageLabMacOS
        path: dist
        
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Windows
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller -F -n=VoltageLabWindows --clean --additional-hooks-dir=. voltage_lab.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VoltageLabWindows
        path: dist