on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Linux
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pyinstaller -F -n=VoltageLabLinux --clean --additional-hooks-dir=. voltage_lab.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VoltageLabLinux
        path: dist

  build_macos:
    runs-on: macos-latest
    env:
      # We need the official Python, because the GA ones only support newer macOS versions.
      # The deployment target is picked up by the Python build tools automatically.
      PYTHON_VERSION: 3.9.1
      MACOSX_DEPLOYMENT_TARGET: 10.9
    steps:
    - uses: actions/checkout@v2
    - name: Get Python
      run: curl https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-macosx10.9.pkg -o "python.pkg"
    - name: Install Python
      # Need to copy the pkg because the installer command removes it, breaking the cache.
      run: |
        sudo installer -pkg python.pkg -target /
    - name: Install Python dependencies and Build
      run: |
        python3 --version
        python3 -m pip install --upgrade pip
        pip3 install --upgrade -r requirements.txt
        python3 -m PyInstaller -F -n=VoltageLabMacOS --clean --additional-hooks-dir=. voltage_lab.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VoltageLabMacOS
        path: dist
        
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Windows
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pyinstaller -F -n=VoltageLabWindows --clean --additional-hooks-dir=. voltage_lab.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VoltageLabWindows
        path: dist
